export enum IconType {
  bottom = 'bottom',
  right = 'right',
  up = 'up',
  left = 'left',
  escape = 'escape',
  mouse = 'mouse',
  phone = 'phone',
  instagram = 'instagram',
  logo = 'logo',
  arrowDown = 'arrowDown',
  close = 'close',
  headphone = 'headphone',
  headphoneMuted = 'headphoneMuted',
  soundKey = 'soundKey',
  a = 'a',
  w = 'w',
  d = 'd',
  s = 's'
}
